In [260]:
import pandas as pd

In [261]:
iris = pd.read_csv("irisdata.csv")
iris

     Sepal Length  Sepal Width  Petal Length  Petal Width     Class Label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [262]:
 iris.head()

   Sepal Length  Sepal Width  Petal Length  Petal Width  Class Label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [263]:
iris.tail()

     Sepal Length  Sepal Width  Petal Length  Petal Width     Class Label
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [264]:
iris.shape

(150, 5)

In [265]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal Length  150 non-null    float64
 1   Sepal Width   150 non-null    float64
 2   Petal Length  150 non-null    float64
 3   Petal Width   150 non-null    float64
 4   Class Label   150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [266]:
iris.describe()

       Sepal Length  Sepal Width  Petal Length  Petal Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [267]:
iris.columns

Index(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Class Label'],
      dtype='object')

In [268]:
iris[['Sepal Length', 'Sepal Width']]

     Sepal Length  Sepal Width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [269]:
iris.rename(columns= {'Sepal Length': 'sepal_len', 'Sepal Width': 'sepal_wid', 'Petal Length': 'petal_len', 'Petal Width': 'petal_wid', 'Class Label': 'class_lab'}, inplace= True)

In [270]:
iris.columns

Index(['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class_lab'], dtype='object')

In [271]:
iris[iris['class_lab'] =='Iris-setosa']

    sepal_len  sepal_wid  petal_len  petal_wid    class_lab
0         5.1        3.5        1.4        0.2  Iris-setosa
1         4.9        3.0        1.4        0.2  Iris-setosa
2         4.7        3.2        1.3        0.2  Iris-setosa
3         4.6        3.1        1.5        0.2  Iris-setosa
4         5.0        3.6        1.4        0.2  Iris-setosa
5         5.4        3.9        1.7        0.4  Iris-setosa
6         4.6        3.4        1.4        0.3  Iris-setosa
7         5.0        3.4        1.5        0.2  Iris-setosa
8         4.4        2.9        1.4        0.2  Iris-setosa
9         4.9        3.1        1.5        0.1  Iris-setosa
10        5.4        3.7        1.5        0.2  Iris-setosa
11        4.8        3.4        1.6        0.2  Iris-setosa
12        4.8        3.0        1.4        0.1  Iris-setosa
13        4.3        3.0        1.1        0.1  Iris-setosa
14        5.8        4.0        1.2        0.2  Iris-setosa
15        5.7        4.4        1.5        0.4  Iris-setosa
16        5.4        3.9        1.3        0.4  Iris-setosa
17        5.1        3.5        1.4        0.3  Iris-setosa
18        5.7        3.8        1.7        0.3  Iris-setosa
19        5.1        3.8        1.5        0.3  Iris-setosa
20        5.4        3.4        1.7        0.2  Iris-setosa
21        5.1        3.7        1.5        0.4  Iris-setosa
22        4.6        3.6        1.0        0.2  Iris-setosa
23        5.1        3.3        1.7        0.5  Iris-setosa
24        4.8        3.4        1.9        0.2  Iris-setosa
25        5.0        3.0        1.6        0.2  Iris-setosa
26        5.0        3.4        1.6        0.4  Iris-setosa
27        5.2        3.5        1.5        0.2  Iris-setosa
28        5.2        3.4        1.4        0.2  Iris-setosa
29        4.7        3.2        1.6        0.2  Iris-setosa
30        4.8        3.1        1.6        0.2  Iris-setosa
31        5.4        3.4        1.5        0.4  Iris-setosa
32        5.2        4.1        1.5        0.1  Iris-setosa
33        5.5        4.2        1.4        0.2  Iris-setosa
34        4.9        3.1        1.5        0.1  Iris-setosa
35        5.0        3.2        1.2        0.2  Iris-setosa
36        5.5        3.5        1.3        0.2  Iris-setosa
37        4.9        3.1        1.5        0.1  Iris-setosa
38        4.4        3.0        1.3        0.2  Iris-setosa
39        5.1        3.4        1.5        0.2  Iris-setosa
40        5.0        3.5        1.3        0.3  Iris-setosa
41        4.5        2.3        1.3        0.3  Iris-setosa
42        4.4        3.2        1.3        0.2  Iris-setosa
43        5.0        3.5        1.6        0.6  Iris-setosa
44        5.1        3.8        1.9        0.4  Iris-setosa
45        4.8        3.0        1.4        0.3  Iris-setosa
46        5.1        3.8        1.6        0.2  Iris-setosa
47        4.6        3.2        1.4        0.2  Iris-setosa
48        5.3        3.7        1.5        0.2  Iris-setosa
49        5.0        3.3        1.4        0.2  Iris-setosa

In [272]:
iris[iris['class_lab'] =='Iris-virginica']

     sepal_len  sepal_wid  petal_len  petal_wid       class_lab
100        6.3        3.3        6.0        2.5  Iris-virginica
101        5.8        2.7        5.1        1.9  Iris-virginica
102        7.1        3.0        5.9        2.1  Iris-virginica
103        6.3        2.9        5.6        1.8  Iris-virginica
104        6.5        3.0        5.8        2.2  Iris-virginica
105        7.6        3.0        6.6        2.1  Iris-virginica
106        4.9        2.5        4.5        1.7  Iris-virginica
107        7.3        2.9        6.3        1.8  Iris-virginica
108        6.7        2.5        5.8        1.8  Iris-virginica
109        7.2        3.6        6.1        2.5  Iris-virginica
110        6.5        3.2        5.1        2.0  Iris-virginica
111        6.4        2.7        5.3        1.9  Iris-virginica
112        6.8        3.0        5.5        2.1  Iris-virginica
113        5.7        2.5        5.0        2.0  Iris-virginica
114        5.8        2.8        5.1        2.4  Iris-virginica
115        6.4        3.2        5.3        2.3  Iris-virginica
116        6.5        3.0        5.5        1.8  Iris-virginica
117        7.7        3.8        6.7        2.2  Iris-virginica
118        7.7        2.6        6.9        2.3  Iris-virginica
119        6.0        2.2        5.0        1.5  Iris-virginica
120        6.9        3.2        5.7        2.3  Iris-virginica
121        5.6        2.8        4.9        2.0  Iris-virginica
122        7.7        2.8        6.7        2.0  Iris-virginica
123        6.3        2.7        4.9        1.8  Iris-virginica
124        6.7        3.3        5.7        2.1  Iris-virginica
125        7.2        3.2        6.0        1.8  Iris-virginica
126        6.2        2.8        4.8        1.8  Iris-virginica
127        6.1        3.0        4.9        1.8  Iris-virginica
128        6.4        2.8        5.6        2.1  Iris-virginica
129        7.2        3.0        5.8        1.6  Iris-virginica
130        7.4        2.8        6.1        1.9  Iris-virginica
131        7.9        3.8        6.4        2.0  Iris-virginica
132        6.4        2.8        5.6        2.2  Iris-virginica
133        6.3        2.8        5.1        1.5  Iris-virginica
134        6.1        2.6        5.6        1.4  Iris-virginica
135        7.7        3.0        6.1        2.3  Iris-virginica
136        6.3        3.4        5.6        2.4  Iris-virginica
137        6.4        3.1        5.5        1.8  Iris-virginica
138        6.0        3.0        4.8        1.8  Iris-virginica
139        6.9        3.1        5.4        2.1  Iris-virginica
140        6.7        3.1        5.6        2.4  Iris-virginica
141        6.9        3.1        5.1        2.3  Iris-virginica
142        5.8        2.7        5.1        1.9  Iris-virginica
143        6.8        3.2        5.9        2.3  Iris-virginica
144        6.7        3.3        5.7        2.5  Iris-virginica
145        6.7        3.0        5.2        2.3  Iris-virginica
146        6.3        2.5        5.0        1.9  Iris-virginica
147        6.5        3.0        5.2        2.0  Iris-virginica
148        6.2        3.4        5.4        2.3  Iris-virginica
149        5.9        3.0        5.1        1.8  Iris-virginica

In [273]:
iris['class_lab'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [274]:
iris[iris['class_lab']== 'Iris-versicolor']

    sepal_len  sepal_wid  petal_len  petal_wid        class_lab
50        7.0        3.2        4.7        1.4  Iris-versicolor
51        6.4        3.2        4.5        1.5  Iris-versicolor
52        6.9        3.1        4.9        1.5  Iris-versicolor
53        5.5        2.3        4.0        1.3  Iris-versicolor
54        6.5        2.8        4.6        1.5  Iris-versicolor
55        5.7        2.8        4.5        1.3  Iris-versicolor
56        6.3        3.3        4.7        1.6  Iris-versicolor
57        4.9        2.4        3.3        1.0  Iris-versicolor
58        6.6        2.9        4.6        1.3  Iris-versicolor
59        5.2        2.7        3.9        1.4  Iris-versicolor
60        5.0        2.0        3.5        1.0  Iris-versicolor
61        5.9        3.0        4.2        1.5  Iris-versicolor
62        6.0        2.2        4.0        1.0  Iris-versicolor
63        6.1        2.9        4.7        1.4  Iris-versicolor
64        5.6        2.9        3.6        1.3  Iris-versicolor
65        6.7        3.1        4.4        1.4  Iris-versicolor
66        5.6        3.0        4.5        1.5  Iris-versicolor
67        5.8        2.7        4.1        1.0  Iris-versicolor
68        6.2        2.2        4.5        1.5  Iris-versicolor
69        5.6        2.5        3.9        1.1  Iris-versicolor
70        5.9        3.2        4.8        1.8  Iris-versicolor
71        6.1        2.8        4.0        1.3  Iris-versicolor
72        6.3        2.5        4.9        1.5  Iris-versicolor
73        6.1        2.8        4.7        1.2  Iris-versicolor
74        6.4        2.9        4.3        1.3  Iris-versicolor
75        6.6        3.0        4.4        1.4  Iris-versicolor
76        6.8        2.8        4.8        1.4  Iris-versicolor
77        6.7        3.0        5.0        1.7  Iris-versicolor
78        6.0        2.9        4.5        1.5  Iris-versicolor
79        5.7        2.6        3.5        1.0  Iris-versicolor
80        5.5        2.4        3.8        1.1  Iris-versicolor
81        5.5        2.4        3.7        1.0  Iris-versicolor
82        5.8        2.7        3.9        1.2  Iris-versicolor
83        6.0        2.7        5.1        1.6  Iris-versicolor
84        5.4        3.0        4.5        1.5  Iris-versicolor
85        6.0        3.4        4.5        1.6  Iris-versicolor
86        6.7        3.1        4.7        1.5  Iris-versicolor
87        6.3        2.3        4.4        1.3  Iris-versicolor
88        5.6        3.0        4.1        1.3  Iris-versicolor
89        5.5        2.5        4.0        1.3  Iris-versicolor
90        5.5        2.6        4.4        1.2  Iris-versicolor
91        6.1        3.0        4.6        1.4  Iris-versicolor
92        5.8        2.6        4.0        1.2  Iris-versicolor
93        5.0        2.3        3.3        1.0  Iris-versicolor
94        5.6        2.7        4.2        1.3  Iris-versicolor
95        5.7        3.0        4.2        1.2  Iris-versicolor
96        5.7        2.9        4.2        1.3  Iris-versicolor
97        6.2        2.9        4.3        1.3  Iris-versicolor
98        5.1        2.5        3.0        1.1  Iris-versicolor
99        5.7        2.8        4.1        1.3  Iris-versicolor

In [275]:
iris['class_lab'].value_counts()

class_lab
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [276]:
iris[['sepal_len', 'sepal_wid']].mean()

sepal_len    5.843333
sepal_wid    3.054000
dtype: float64

In [277]:
iris[['sepal_len', 'sepal_wid']].max()

sepal_len    7.9
sepal_wid    4.4
dtype: float64

In [278]:
iris[['sepal_len', 'sepal_wid']].min()

sepal_len    4.3
sepal_wid    2.0
dtype: float64

In [279]:
iris[['petal_len', 'petal_wid']].mean()

petal_len    3.758667
petal_wid    1.198667
dtype: float64

In [280]:
iris[['petal_len', 'petal_wid']].max()

petal_len    6.9
petal_wid    2.5
dtype: float64

In [281]:
iris[['petal_len', 'petal_wid']].min()

petal_len    1.0
petal_wid    0.1
dtype: float64

## groupby and aggregate function

In [295]:
iris.columns

Index(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width'], dtype='object')

In [316]:
iris.rename(columns= {'Sepal Length': 'sepal_len', 'Sepal Width': 'sepal_wid', 'Petal Length': 'petal_len', 'Petal Width': 'petal_wid', 'Class Label': 'class_lab'}, inplace= True)
iris.columns

Index(['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class_lab'], dtype='object')

In [317]:
iris.groupby('class_lab').sum()

                 sepal_len  sepal_wid  petal_len  petal_wid
class_lab
Iris-setosa          250.3      170.9       73.2       12.2
Iris-versicolor      296.8      138.5      213.0       66.3
Iris-virginica       329.4      148.7      277.6      101.3

In [283]:
iris = pd.read_csv('irisdata.csv')
iris.columns

Index(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Class Label'],
      dtype='object')

In [285]:
iris.groupby('Class Label').mean()

                 Sepal Length  Sepal Width  Petal Length  Petal Width
Class Label
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [286]:
iris.groupby('Class Label').max()

                 Sepal Length  Sepal Width  Petal Length  Petal Width
Class Label
Iris-setosa               5.8          4.4           1.9          0.6
Iris-versicolor           7.0          3.4           5.1          1.8
Iris-virginica            7.9          3.8           6.9          2.5

In [287]:
iris.groupby('Class Label').min()

                 Sepal Length  Sepal Width  Petal Length  Petal Width
Class Label
Iris-setosa               4.3          2.3           1.0          0.1
Iris-versicolor           4.9          2.0           3.0          1.0
Iris-virginica            4.9          2.2           4.5          1.4

In [319]:
iris.rename(columns= {'Sepal Length': 'sepal_len', 'Sepal Width': 'sepal_wid', 'Petal Length': 'petal_len', 'Petal Width': 'petal_wid', 'Class Label': 'class_lab'}, inplace= True)

iris.groupby('class_lab')[['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid']].agg(['mean', 'max', 'min'])

                sepal_len           sepal_wid           petal_len            \
                     mean  max  min      mean  max  min      mean  max  min
class_lab
Iris-setosa         5.006  5.8  4.3     3.418  4.4  2.3     1.464  1.9  1.0
Iris-versicolor     5.936  7.0  4.9     2.770  3.4  2.0     4.260  5.1  3.0
Iris-virginica      6.588  7.9  4.9     2.974  3.8  2.2     5.552  6.9  4.5

                petal_wid
                     mean  max  min
class_lab
Iris-setosa         0.244  0.6  0.1
Iris-versicolor     1.326  1.8  1.0
Iris-virginica      2.026  2.5  1.4

## Indexing

In [307]:
# column indexing
iris.columns
#iris['petal_len']

Index(['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width',
       'Class Label'],
      dtype='object')

In [308]:
iris.rename(columns= {'Sepal Length': 'sepal_len', 'Sepal Width': 'sepal_wid', 'Petal Length': 'petal_len', 'Petal Width': 'petal_wid', 'Class Label': 'class_lab'}, inplace= True)
iris

     sepal_len  sepal_wid  petal_len  petal_wid       class_lab
0          5.1        3.5        1.4        0.2     Iris-setosa
1          4.9        3.0        1.4        0.2     Iris-setosa
2          4.7        3.2        1.3        0.2     Iris-setosa
3          4.6        3.1        1.5        0.2     Iris-setosa
4          5.0        3.6        1.4        0.2     Iris-setosa
..         ...        ...        ...        ...             ...
145        6.7        3.0        5.2        2.3  Iris-virginica
146        6.3        2.5        5.0        1.9  Iris-virginica
147        6.5        3.0        5.2        2.0  Iris-virginica
148        6.2        3.4        5.4        2.3  Iris-virginica
149        5.9        3.0        5.1        1.8  Iris-virginica

[150 rows x 5 columns]

In [309]:
iris.columns
iris[['petal_len','petal_wid']]

     petal_len  petal_wid
0          1.4        0.2
1          1.4        0.2
2          1.3        0.2
3          1.5        0.2
4          1.4        0.2
..         ...        ...
145        5.2        2.3
146        5.0        1.9
147        5.2        2.0
148        5.4        2.3
149        5.1        1.8

[150 rows x 2 columns]

In [310]:
# row indeing by position
iris.iloc[0]

sepal_len            5.1
sepal_wid            3.5
petal_len            1.4
petal_wid            0.2
class_lab    Iris-setosa
Name: 0, dtype: object

In [311]:
iris.iloc[0:5]

   sepal_len  sepal_wid  petal_len  petal_wid    class_lab
0        5.1        3.5        1.4        0.2  Iris-setosa
1        4.9        3.0        1.4        0.2  Iris-setosa
2        4.7        3.2        1.3        0.2  Iris-setosa
3        4.6        3.1        1.5        0.2  Iris-setosa
4        5.0        3.6        1.4        0.2  Iris-setosa

In [ ]:
# row indexing by label
iris.loc[0]

In [312]:
iris.loc[0:5]

   sepal_len  sepal_wid  petal_len  petal_wid    class_lab
0        5.1        3.5        1.4        0.2  Iris-setosa
1        4.9        3.0        1.4        0.2  Iris-setosa
2        4.7        3.2        1.3        0.2  Iris-setosa
3        4.6        3.1        1.5        0.2  Iris-setosa
4        5.0        3.6        1.4        0.2  Iris-setosa
5        5.4        3.9        1.7        0.4  Iris-setosa

In [313]:
iris.loc[:, 'petal_len']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_len, Length: 150, dtype: float64

In [314]:
iris[iris['petal_len'] > 4]

     sepal_len  sepal_wid  petal_len  petal_wid        class_lab
50         7.0        3.2        4.7        1.4  Iris-versicolor
51         6.4        3.2        4.5        1.5  Iris-versicolor
52         6.9        3.1        4.9        1.5  Iris-versicolor
54         6.5        2.8        4.6        1.5  Iris-versicolor
55         5.7        2.8        4.5        1.3  Iris-versicolor
..         ...        ...        ...        ...              ...
145        6.7        3.0        5.2        2.3   Iris-virginica
146        6.3        2.5        5.0        1.9   Iris-virginica
147        6.5        3.0        5.2        2.0   Iris-virginica
148        6.2        3.4        5.4        2.3   Iris-virginica
149        5.9        3.0        5.1        1.8   Iris-virginica

[84 rows x 5 columns]

In [315]:
iris[(iris['petal_len'] > 4) & (iris['petal_wid'] > 1)]

     sepal_len  sepal_wid  petal_len  petal_wid        class_lab
50         7.0        3.2        4.7        1.4  Iris-versicolor
51         6.4        3.2        4.5        1.5  Iris-versicolor
52         6.9        3.1        4.9        1.5  Iris-versicolor
54         6.5        2.8        4.6        1.5  Iris-versicolor
55         5.7        2.8        4.5        1.3  Iris-versicolor
..         ...        ...        ...        ...              ...
145        6.7        3.0        5.2        2.3   Iris-virginica
146        6.3        2.5        5.0        1.9   Iris-virginica
147        6.5        3.0        5.2        2.0   Iris-virginica
148        6.2        3.4        5.4        2.3   Iris-virginica
149        5.9        3.0        5.1        1.8   Iris-virginica

[83 rows x 5 columns]

In [2]:
import sklearn
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

In [4]:
# load dataset
X = iris.data
y = iris.target   # actual class labels

# apply KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X)

# visualization (using petal features)
plt.scatter(X[:,2], X[:,3], c=clusters)
plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.title("K-Means Clustering on Iris Dataset")
plt.show()

NameError: name 'iris' is not defined